### ISSUE TITLE
Allow to configure system sender address

### ISSUE THREAD

**Issue by mawoka-myblock** [muety/mailwhale#17]
So, in my setup, I use an email-provider which doesn't allow sending a mail under a different name. For example, Mailwhale uses the mail-adress `system@host.name` but my email my email-provider is `hans-noreply@hans.wurst` and the host doesn't allow sending mails under `system@host.name`. The result is that the server rejects the mail. 

## Solution
Make the sender-mail changable.

**Comment by mawoka-myblock** [comment]
A new thought: Only allow one mail and don't create aliases automatically

**Comment by muety** [comment]
Just to clarify for the report: this mainly affects mails sent from the system user, i.e. user- and sender verification mails. For any other mails, a client with a custom sender address can be created. I'll push an update to allow configuring the system sender address.
