### ISSUE TITLE
Cannot send email verification (no templates found)

### ISSUE THREAD

**Issue by msalmanfarisi** [muety/mailwhale#19]
Hello,
I already tried MailWhale on docker. Signup failed and no any email verifications sent.
The error from logs :

**[ERROR] failed to send user verification to 'user@example.com': open templates/user_verification.tpl.html: no such file or directory**

please advise and thank you

**Comment by muety** [comment]
Hi, thanks for bringing this up. Please set `env: prod` in `config.yml`, that's going to fix the problem. I'll adapt the README.

**Comment by muety** [comment]
Okay sorry, I think this won't help. I'll adjust the Docker build.
