### ISSUE TITLE
error auth api  and failed to send user verification

### ISSUE THREAD

**Issue by jams008** [muety/mailwhale#21]
Hi, i have an auth problem every time i finish creating my account i can't log in. 
I checked on the db also there is data. 
Can you help me. thanks.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/26858550/150514139-3408cf8a-74e0-48f3-a3bb-fc6e28e74589.png">

**Comment by muety** [comment]
Hi @jams008, can you please show your config (with all sensitive information redacted)?

**Comment by jams008** [comment]
Hi,
Thank you for responding to me. i've found the cause after i use ENV flag from docker it can work fine.

**Comment by jams008** [comment]
but I encountered a new problem, I tried to send mail but it didn't work and the log status was error 500. I don't understand what that means? Is my account smtp the problem?
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/26858550/150525924-a2bcb52c-af55-49ba-ac1b-a1aec8ee759f.png">
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/26858550/150526117-0f557859-ea2a-4d44-9c6e-10714d6a86a2.png">

**Comment by muety** [comment]
I would expect something with your SMTP config to be wrong. Maybe you have to switch `TLS` on / off? What is your mail provider?

**Comment by jams008** [comment]
okay, I'll try to recheck and I'll try to change the smtp provider for a trial.  currently i use self host mail server for smtp.

I am very grateful. I really appreciate your work

**Comment by jams008** [comment]
Hi, after I changed the SMTP account all went well. thank you
