### ISSUE TITLE
I am here to contribute

### ISSUE THREAD

**Issue by iAziz786** [muety/mailwhale#23]
Hi!

I can across MailWhale when I was trying to find [open source alternative to SendGrid](https://alternativeto.net/software/sendgrid/?license=opensource). I also was considering to use Postal but due to its complexity I was thinking to creating something like that in Go and Svelte. Fortunately, in particular project has both. I am happy that I came across this project.

As this project is at its early stage of the development, I was hoping if I can help in the development in any way possible. I am interested and wanting to contribute. So if you have any work to assign to anyone please feel free to let me know.

**Comment by muety** [comment]
HI @iAziz786, thanks a lot for offering your help, I appreciate it! Best would be for you to just start using MailWhale four yourself and I'd assume you'll automatically come across one or the other thing that you might want to improve. Other than that, an good starting issue to go about would perhaps be #10.

That said, https://emailengine.app an other cool tool I just recently came across, that I consider a good MailWhale alternative. You might want to check it out, too.

**Comment by muety** [comment]
I actually already use this in production at https://wakapi.dev and https://anchr.io.

**Comment by iAziz786** [comment]
Okay, then it is little encouraging. Let me try running it in my local. 

I will come with my queries soon. Thanks!

**Comment by muety** [comment]
I'll close this ticket though.
