### ISSUE TITLE
How to create the smtp server?

### ISSUE THREAD

**Issue by iAziz786** [muety/mailwhale#24]
While trying this project in my local, when I try to signup for the first time it tries to send an email for the verification. That email is not getting sent because there is nothing running on `localhost:465`. I was thinking that this project will provide the SMTP server as well. If not by this project, then can you please tell me how can I run an SMTP server on my local which sends the email?

**Comment by muety** [comment]
MailWhale does intentionally not bring its own SMTP server (other than Postal, Cutlefish,...), but is meant to be used with services like GMail, Outlook.com, mailbox.org, etc.
