### ISSUE TITLE
Provide official Docker image

### ISSUE THREAD

**Issue by muety** [muety/mailwhale#28]
Assume there will be Git tags corresponding to program versions. Every time a new tag is pushed, a Docker image shall be built and published to GHCR (not to DockerHub, though). 

Very similar to https://github.com/muety/wakapi/blob/master/.github/workflows/docker.yml.

**Comment by gliptak** [comment]
I can submit a PR like

https://github.com/gliptak/aws-cdk-python/tree/master/.github/workflows

First step might be to merge https://github.com/muety/mailwhale/pull/26
