### ISSUE TITLE
How to create user via the API?

### ISSUE THREAD

**Issue by opensorceror** [muety/mailwhale#34]
Hi! The README mentions:
> To get started with MailWhale, you need to create a user first. To do so, register a new user API or web UI.

Would you be able to provide an example API request for registering a new user using the API? Thanks in advance.

**Comment by muety** [comment]
Sorry, here is an example request, hope that helps!

```bash
curl -XPOST 'http://localhost:3000/api/user' \
    -H 'Content-Type: application/json' \
    --data-raw '{
        "email": "john.doe@example.org",
        "password": "ssshhh"
    }'
```

**Comment by opensorceror** [comment]
Thanks! I did figure it out after digging through the code :) 

Do you mind if I submit a PR that adds it to the README?

**Comment by muety** [comment]
Please do!
