### ISSUE TITLE
Allow to run under subpath with reverse proxy

### ISSUE THREAD

**Issue by riaanp78** [muety/mailwhale#43]
Love this project! trying to setup a reverse proxy using sub directory. Was wondering if mailwhale supports it?

This is the config I am using:

```
    location /mailwhale/ {
        proxy_pass http://127.0.0.1:3005;
        proxy_set_header Host iot.rplab.xyz;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
```
Any hints?

**Comment by muety** [comment]
Looks about right. What specific errors are you getting with that config?

**Comment by riaanp78** [comment]
no errors. everything starts up fine. I can access it directly from it's port (works) , but via reverse proxy I get a blank page 

![image](https://user-images.githubusercontent.com/15311970/218771867-08c34cc6-30ec-470a-8f5e-514d9c15ef82.png)

Using webconsole it looks like it is trying to load files from the root file system e.g. / instead of /mailwhale/

**Comment by riaanp78** [comment]
Thank you! Not strictly required, but great if it could.

**Comment by muety** [comment]
Added support for running behind reverse proxy under a subpath :heavy_check_mark: Check README for instructions.

**Comment by riaanp78** [comment]
Thank you so much. Will check it out
