### ISSUE TITLE
Website Dashbord isn't loading

### ISSUE THREAD

**Issue by FuckingToasters** [muety/mailwhale#45]
Hello, I've sucessfully installed everything and are able to run it without ny issue, when i visit the site then in the console it give the statuscode 200. the website title changed correctly to Mailwhale BUT the page is just blank without any content. Aftr inspecting the HTML of the Pageit seem like there is nothing: 
![grafik](https://user-images.githubusercontent.com/94435104/228809916-a22572bf-3ffa-494e-b0df-6bbf0a805f40.png)

Now i tried to disable adblock or any other extension which could cause this but sadly did not help. I even tried to visit the site on another machine but the issue is always the same.

Note that i changed all 127.0,0.1 in the config to 0.0.0.0 so i can access it outside of the host (cause my linux server don't have an display installed)

Hopefully someone can help me there,

Regards,
FuckingToasters

**Comment by muety** [comment]
Do you see any error messages in the browser console?

**Comment by FuckingToasters** [comment]
Update: After adding the actual server's public address as url it show correctly.

I want to implement the smtp stuff into my mybb forum but it seem like that MailWhale only provide an API for it. Is there a way to get the smpt details and then use smpt directly?

**Comment by muety** [comment]
I think MailWhale is the wrong thing for you. MailWhale takes an already existing SMTP Server (e.g. Gmail) and essentially adds a REST API on top. If you want to send mail via SMTP directly, there's no point in using MailWhale.
